# VLASH Training Configuration for PI05 with Async Inference

# Policy configuration
policy:
  type: pi05
  pretrained_path: lerobot/pi05_base
  push_to_hub: false
  dtype: bfloat16
  device: cuda
  state_cond: true

# Dataset configuration
dataset:
  repo_id: <your dataset repository id>
  video_backend: torchcodec

# Training parameters
output_dir: outputs/train/pi05_async
job_name: pi05_async
batch_size: 16
steps: 50000
num_workers: 4
seed: 1000

# Optimizer configuration
use_policy_training_preset: false
optimizer:
  type: adamw
  lr: 5.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-10

# Learning rate scheduler
scheduler:
  type: cosine_decay_with_warmup
  num_warmup_steps: 1000
  peak_lr: 5.0e-5
  decay_lr: 2.5e-6
  num_decay_steps: 50000

# Checkpointing
save_checkpoint: true
save_freq: 10000

# Logging
log_freq: 200
wandb:
  enable: true
  project: vlash
  entity: null
  disable_artifact: true

# Maximum temporal delay steps
# Set to N to enable random delays from [0, N]
max_delay_steps: 8

# Enable shared observation optimization
# When true, trains all offsets [0, max_delay_steps] together with shared
# observation embeddings instead of randomly sampling one offset per sample
shared_observation: true