# VLASH Training Configuration for PI0
# Standard training without future-state-awareness

# Policy configuration
policy:
  type: pi0
  pretrained_path: lerobot/pi0_base
  push_to_hub: false
  dtype: bfloat16
  device: cuda

# Dataset configuration
dataset:
  repo_id: 
  video_backend: torchcodec

# Training parameters
output_dir: outputs/train/pi0
job_name: pi0
batch_size: 8
steps: 50000
num_workers: 4
seed: 1000

# Optimizer configuration
use_policy_training_preset: false
optimizer:
  type: adamw
  lr: 5.0e-5
  betas: [0.9, 0.95]
  weight_decay: 1.0e-10

# Learning rate scheduler
scheduler:
  type: cosine_decay_with_warmup
  num_warmup_steps: 1000
  peak_lr: 5.0e-5
  decay_lr: 2.5e-6
  num_decay_steps: 50000

# Checkpointing
save_checkpoint: true
save_freq: 10000
eval_freq: 10000

# Logging
log_freq: 200
wandb:
  enable: true
  project: vlash
  entity: null

# Maximum temporal delay steps
# Set to N to enable random delays from [0, N]
max_delay_steps: 0